version: '3.9'

services:
  myapp:
    build: .
    container_name: myapp
    volumes:
      - .:/py
    ports:
      - "5000:5000"

  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    network_mode: "bridge"
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - D:\docker\portainer\data:/data